/**
 * A deliberately tiny markdown renderer with an allowlist.
 *
 * ============================================================================
 * WHY NOT marked / markdown-it / react-markdown
 * ============================================================================
 *
 * Two reasons, and the second is the serious one.
 *
 * 1. SIZE. The bundle budget is 25 KB gzipped for the entire widget. marked is
 *    ~12 KB and react-markdown with remark is far more. Spending half the budget
 *    on formatting is not a trade worth making for text that is bold, italic,
 *    a list, or a link.
 *
 * 2. SAFETY. Those libraries render whatever they are given, and several
 *    support raw HTML passthrough by default. The text arriving here was
 *    generated by a language model that has just read retrieved documents and
 *    Shopify product descriptions — content the store owner may not have
 *    written. That is an injection path ending in `innerHTML` on a merchant's
 *    live storefront, next to their checkout.
 *
 * So this produces a TREE, not a string, and the caller renders it with React.
 * There is no `dangerouslySetInnerHTML` anywhere in this widget, which means no
 * amount of creative markup in a product description can become an element.
 *
 * Anything not on the allowlist renders as literal text. That is the correct
 * failure mode: a customer seeing a stray asterisk is a cosmetic bug, and a
 * customer's session token leaving the page is not.
 */

export type Inline =
  | { readonly kind: "text"; readonly value: string }
  | { readonly kind: "strong"; readonly value: string }
  | { readonly kind: "em"; readonly value: string }
  | { readonly kind: "code"; readonly value: string }
  | { readonly kind: "link"; readonly value: string; readonly href: string };

export type Block =
  | { readonly kind: "paragraph"; readonly spans: readonly Inline[] }
  | { readonly kind: "list"; readonly items: readonly (readonly Inline[])[] }
  /**
   * A real table, because the size chart IS one.
   *
   * Without this, "| Set size | Thumb | Index |" renders as literal pipes and
   * dashes — the single most important piece of content this bot serves,
   * displayed as junk. Worth the ~400 bytes.
   */
  | { readonly kind: "table"; readonly header: readonly string[]; readonly rows: readonly (readonly string[])[] };

/**
 * Only https, and only as an absolute URL.
 *
 * `javascript:`, `data:` and `vbscript:` are all executable in an href. A
 * protocol-relative `//evil.com` inherits the page's scheme and is a real
 * phishing vector on a storefront — the customer sees a link on nailzify.com.
 */
function safeHref(raw: string): string | null {
  const href = raw.trim();
  if (!href.startsWith("https://")) return null;
  try {
    const url = new URL(href);
    return url.protocol === "https:" ? url.href : null;
  } catch {
    return null;
  }
}

const INLINE_PATTERN =
  /(\*\*([^*]+)\*\*)|(\*([^*]+)\*)|(`([^`]+)`)|(\[([^\]]+)\]\(([^)\s]+)\))/g;

function parseInline(text: string): readonly Inline[] {
  const spans: Inline[] = [];
  let cursor = 0;

  for (const match of text.matchAll(INLINE_PATTERN)) {
    const start = match.index;
    if (start > cursor) {
      spans.push({ kind: "text", value: text.slice(cursor, start) });
    }

    const [, , strong, , em, , code, , linkText, linkHref] = match;

    if (strong !== undefined) spans.push({ kind: "strong", value: strong });
    else if (em !== undefined) spans.push({ kind: "em", value: em });
    else if (code !== undefined) spans.push({ kind: "code", value: code });
    else if (linkText !== undefined && linkHref !== undefined) {
      const href = safeHref(linkHref);
      // A rejected URL keeps its TEXT and loses its link. Dropping the text
      // entirely would silently delete part of an answer.
      spans.push(href ? { kind: "link", value: linkText, href } : { kind: "text", value: linkText });
    }

    cursor = start + match[0].length;
  }

  if (cursor < text.length) spans.push({ kind: "text", value: text.slice(cursor) });
  return spans;
}

/** `| a | b |` -> ["a","b"]. Leading/trailing pipes are optional in the wild. */
const splitRow = (line: string): string[] =>
  line.replace(/^\||\|$/g, "").split("|").map((cell) => cell.trim());

/** The `|---|:--:|` line that turns the row above it into a header. */
const isDivider = (line: string): boolean =>
  /^\|?[\s:|-]+\|[\s:|-]*$/.test(line) && line.includes("-");

export function parseMarkdown(source: string): readonly Block[] {
  const blocks: Block[] = [];
  let listBuffer: (readonly Inline[])[] = [];

  const flushList = () => {
    if (listBuffer.length > 0) {
      blocks.push({ kind: "list", items: listBuffer });
      listBuffer = [];
    }
  };

  // Blank-line separated, so a streaming half-paragraph still renders.
  const lines = source.split("\n");

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i]!.trim();

    if (line.length === 0) {
      flushList();
      continue;
    }

    // ---- table ------------------------------------------------------------
    // Requires the divider line to be present. Mid-stream, a header row arrives
    // before its divider — treating it as a table then would render a one-row
    // table that reflows a moment later. Waiting means it briefly shows as text
    // and then snaps into a table, which is the calmer of the two.
    if (line.startsWith("|") && isDivider(lines[i + 1]?.trim() ?? "")) {
      flushList();
      const header = splitRow(line);
      const rows: string[][] = [];

      let j = i + 2;
      for (; j < lines.length; j += 1) {
        const row = lines[j]!.trim();
        if (!row.startsWith("|")) break;
        rows.push(splitRow(row));
      }

      blocks.push({ kind: "table", header, rows });
      i = j - 1;
      continue;
    }

    const bullet = /^[-*+]\s+(.*)$/.exec(line) ?? /^\d+[.)]\s+(.*)$/.exec(line);
    if (bullet?.[1]) {
      listBuffer.push(parseInline(bullet[1]));
      continue;
    }

    flushList();

    // Headings are flattened to bold paragraphs. A model writing "## Returns"
    // inside a chat bubble should not produce storefront-sized display type,
    // and inheriting the merchant's h2 styling is worse still.
    const heading = /^#{1,6}\s+(.*)$/.exec(line);
    const content = heading?.[1] ?? line;

    blocks.push({
      kind: "paragraph",
      spans: heading ? [{ kind: "strong", value: content }] : parseInline(content),
    });
  }

  flushList();
  return blocks;
}
